clc; clear all; home;

% define the data set folder
dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'full-sphere');

%% Load the data
[~, ~, magnetometer, temperature] = loadData(dataSetFolder);

% Fetch axes
x = magnetometer.Data(:, 1);
y = magnetometer.Data(:, 3); % fix for HMC5883L
z = magnetometer.Data(:, 2); % fix for HMC5883L
N = size(x, 1);

% Calibrate sensor
[correction, xc, yc, zc] = calibrateByEllipseFitting(x, y, z);

% Apply combined correction matrix
for i=1:N
    v    = correction * [x(i); y(i); z(i); 1];
    xc(i) = v(1);
    yc(i) = v(2);
    zc(i) = v(3);
end

% Apply transformation to affine test vector
test = [-correction(1:3,4); 1] + [1; 0; 0; 0];
test = correction * test;


%% Plot data
figureHandle = figure('Name', 'Raw sensor data', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis
lineColor(4, :) = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

%% Compass
% compass: x/y axis
axisCompass(1) = subplot(3, 3, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'Color', plotBackground ...
    );

line(x, y, ...
    'Parent', axisCompass(1), ...
    'Color', lineColor(4, :) ...
    );
hold on;

axis square;
xlim([-1 1]);
ylim([-1 1]);
rotate3d;

title('x/y plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');

% compass: x/z axis
axisCompass(2) = subplot(3, 3, 4, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

line(x, z, ...
    'Parent', axisCompass(2), ...
    'Color', lineColor(4, :) ...
    );

axis square;
xlim([-1 1]);
ylim([-1 1]);

title('x/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_z [Gs]');

% compass: y/z axis
axisCompass(3) = subplot(3, 3, 7, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(2, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

line(y, z, ...
    'Parent', axisCompass(3), ...
    'Color', lineColor(4, :) ...
    );

axis square;
xlim([-1 1]);
ylim([-1 1]);

title('y/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_y [Gs]');
ylabel('B_z [Gs]');

%% Compass
% compass: x, y and z axis
axisCompass(4) = subplot(3, 3, [2 3 5 6 8 9], ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'ZGrid', 'on', ...
    'ZColor', lineColor(3, :), ...
    'Color', plotBackground, ...
    'LineStyle', ':' ...
    );

lol = line(x, y, z, ...
    'Parent', axisCompass(4), ...
    'Color', lineColor(4, :)*0.5...
    );

view(3);
axis square;
xlim([-1 1]);
ylim([-1 1]);
zlim([-1 1]);

hold on;
line(xc, ...
    yc, ...
    zc, ...
    'Parent', axisCompass(4), ...
    'Color', [0.9 0.5 0], ...
    'LineStyle', '-' ...
    );

line([-correction(1,4) -correction(1,4)+1], ...
    [-correction(2,4) -correction(2,4)], ...
    [-correction(3,4) -correction(3,4)], ...
    'Parent', axisCompass(4), ...
    'Color', [0.7 0.7 0.7], ...
    'LineStyle', ':' ...
    );

line([0 test(1)], ...
    [0 test(2)], ...
    [0 test(3)], ...
    'Parent', axisCompass(4), ...
    'Color', [0.9 0.9 0.9], ...
    'LineStyle', '-' ...
    );

title('HMC5883L Magnetometer', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');
zlabel('B_z [Gs]');
