clear all; home;

% define the data set folder
dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'unmoved-with-x-pointing-forward-10min');
performOffsetCorrection = true;

%% Load the data
[accelerometer, ~, ~, ~] = loadData(dataSetFolder, true);
time = accelerometer.Time;

%% Derive additional data from raw input by integrating
scaleg2a = 9.81; % g to m/2^2
acceleration = accelerometer.Data(:,1:3)*scaleg2a;

% Subtract mean from acceleration to get linear acceleration 
% (which should be zero)
acceleration = acceleration - ones(size(acceleration, 1), 1)*mean(acceleration);

% Get derived data
velocity =     cumsum(acceleration(:,1:3));
position =     cumsum(velocity(:,1:3));

%% Plot data
figureHandle = figure('Name', 'Raw and derived inertial sensor data', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis
meanColor = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

%% Acceleration
% acceleration: x axis
axisAccel(1) = subplot(3, 3, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
x = acceleration(:, 1);
line(t, x, ...
    'Parent', axisAccel(1), ...
    'Color', lineColor(1, :) ...
    ); 

xlim([0 t(end)]);

title('Acceleration', ...
    'Color', titleColor ...
    );
ylabel('a_x [g]');
xlabel('t [s]');

% acceleration: y axis
axisAccel(2) = subplot(3, 3, 4, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
y = acceleration(:, 2);
line(t, y, ...
    'Parent', axisAccel(2), ...
    'Color', lineColor(2, :) ...
    );

xlim([0 t(end)]);

ylabel('a_y [g]');
xlabel('t [s]');

% acceleration: z axis
axisAccel(3) = subplot(3, 3, 7, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
z = acceleration(:, 3);
line(t, z, ...
    'Parent', axisAccel(3), ...
    'Color', lineColor(3, :) ...
    );

xlim([0 t(end)]);

ylabel('a_z [g]');
xlabel('t [s]');

%% Velocity
% velocity: x axis
axisVelocity(1) = subplot(3, 3, 2, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
x = velocity(:, 1);
line(t, x, ...
    'Parent', axisVelocity(1), ...
    'Color', lineColor(1, :) ...
    );

xlim([0 t(end)]);

title('Velocity', ...
    'Color', titleColor ...
    );
ylabel('v_x [m/s]');
xlabel('t [s]');

% velocity: y axis
axisVelocity(2) = subplot(3, 3, 5, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
y = velocity(:, 2);
line(t, y, ...
    'Parent', axisVelocity(2), ...
    'Color', lineColor(2, :) ...
    );

xlim([0 t(end)]);

ylabel('a_y [m/s]');
xlabel('t [s]');

% velocity: z axis
axisVelocity(3) = subplot(3, 3, 8, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
z = velocity(:, 3);
line(t, z, ...
    'Parent', axisVelocity(3), ...
    'Color', lineColor(3, :) ...
    );

xlim([0 t(end)]);

ylabel('a_z [m/s]');
xlabel('t [s]');

%% Position
% position: x axis
axisPosition(1) = subplot(3, 3, 3, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
x = position(:, 1);
line(t, x, ...
    'Parent', axisPosition(1), ...
    'Color', lineColor(1, :) ...
    );

xlim([0 t(end)]);

title('Position', ...
    'Color', titleColor ...
    );
ylabel('s_x [m]');
xlabel('t [s]');

% position: y axis
axisPosition(2) = subplot(3, 3, 6, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
y = position(:, 2);
line(t, y, ...
    'Parent', axisPosition(2), ...
    'Color', lineColor(2, :) ...
    );

xlim([0 t(end)]);

ylabel('s_y [m]');
xlabel('t [s]');

% velocity: z axis
axisPosition(3) = subplot(3, 3, 9, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
z = position(:, 3);
line(t, z, ...
    'Parent', axisPosition(3), ...
    'Color', lineColor(3, :) ...
    );

xlim([0 t(end)]);

ylabel('s_z [m]');
xlabel('t [s]');

%% Plot refining
% link the axes
linkaxes([axisAccel axisVelocity axisPosition], 'x');