clear all; home;

%% Load the data
dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'roll-and-tilt-at-45-90');
%dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'rotate-ccw-around-z-pointing-up');
%dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'rotate-ccw-around-y-pointing-left');
%dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'rotate-ccw-around-x-pointing-forward');

% THIS is a DESTROYER
%dataSetFolder = fullfile(fileparts(which(mfilename)), '..' , '..', 'data', 'set-2', 'rotate-ccw-around-x-pointing-up');

[accelerometer, ~, compass, ~] = loadData(dataSetFolder, true);

% resample the time series
[acceleration, compass] = lerpTimeSeries(accelerometer, compass);

% extract time vector
time = acceleration.Time;
N = acceleration.Length;

%% Get roll, pitch and yaw
disp('Looping ...');
ypr = zeros(N, 3);
ypr2 = zeros(N, 3);
quat = zeros(N, 4);
for i=1:N   
    a = acceleration.Data(i, :);
    m = compass.Data(i, :);
    [yaw, pitch, roll, DCM, c, q] = yawPitchRoll(a, m);
    ypr(i, :) = [yaw(1) pitch(1) roll(1)];
    ypr2(i, :) = [yaw(2) pitch(2) roll(2)];
    quat(i, :) = q;
    
    %if time(i) > 7
        %disp(num2str(DCM));
    %end
end

%{
% correct yaw for modulo breaks
yawDiff = diff(ypr(:,1));
indices = find(yawDiff < -90);
yawDiff(indices) = yawDiff(indices) + 360;
indices = find(yawDiff > 90);
yawDiff(indices) = yawDiff(indices) - 360;
ypr(:,1) = [0; cumsum(yawDiff(:))] + ypr(1,1);

% correct pitch for modulo breaks
pitchDiff = diff(ypr(:,2));
indices = find(pitchDiff < -90);
pitchDiff(indices) = pitchDiff(indices) + 360;
indices = find(pitchDiff > 90);
pitchDiff(indices) = pitchDiff(indices) - 360;
ypr(:,2) = [0; cumsum(pitchDiff(:))] + ypr(1,2);

% correct rool for modulo breaks
rollDiff = diff(ypr(:,3));
indices = find(rollDiff < -90);
rollDiff(indices) = rollDiff(indices) + 360;
indices = find(rollDiff > 90);
rollDiff(indices) = rollDiff(indices) - 360;
ypr(:,3) = [0; cumsum(rollDiff(:))] + ypr(1,3);
%}

%% Plot data
figureHandle = figure('Name', 'Raw and derived inertial sensor data', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis

lineColor(4, :) = [1 1 0]; % x axis
lineColor(5, :) = [1 0 1]; % y axis
lineColor(6, :) = [1.0 0.75 0.25]; % z axis

meanColor = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

%% Acceleration
% acceleration: x axis
axisAccel(1) = subplot(3, 4, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
x = acceleration.Data(:, 1);
line(t, x, ...
    'Parent', axisAccel(1), ...
    'Color', lineColor(1, :) ...
    ); 

xlim([0 t(end)]);
ylim([-2 2]);

title('Acceleration', ...
    'Color', titleColor ...
    );
ylabel('a_x [g]');
xlabel('t [s]');

% acceleration: y axis
axisAccel(2) = subplot(3, 4, 5, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
y = acceleration.Data(:, 2);
line(t, y, ...
    'Parent', axisAccel(2), ...
    'Color', lineColor(2, :) ...
    );

xlim([0 t(end)]);
ylim([-2 2]);

ylabel('a_y [g]');
xlabel('t [s]');

% acceleration: z axis
axisAccel(3) = subplot(3, 4, 9, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
z = acceleration.Data(:, 3);
line(t, z, ...
    'Parent', axisAccel(3), ...
    'Color', lineColor(3, :) ...
    );

xlim([0 t(end)]);
ylim([-2 2]);

ylabel('a_z [g]');
xlabel('t [s]');

%% Magnetometer
% compass: x axis
axisCompass(1) = subplot(3, 4, 2, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
x = compass.Data(:, 1);
line(t, x, ...
    'Parent', axisCompass(1), ...
    'Color', lineColor(1, :) ...
    ); 

xlim([0 t(end)]);
ylim([-2 2]);

title('Magnetometer', ...
    'Color', titleColor ...
    );
ylabel('a_x [g]');
xlabel('t [s]');

% compass: y axis
axisCompass(2) = subplot(3, 4, 6, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
y = compass.Data(:, 2);
line(t, y, ...
    'Parent', axisCompass(2), ...
    'Color', lineColor(2, :) ...
    );

xlim([0 t(end)]);
ylim([-2 2]);

ylabel('a_y [g]');
xlabel('t [s]');

% compass: z axis
axisCompass(3) = subplot(3, 4, 10, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
z = compass.Data(:, 3);
line(t, z, ...
    'Parent', axisCompass(3), ...
    'Color', lineColor(3, :) ...
    );

xlim([0 t(end)]);
ylim([-2 2]);

ylabel('a_z [g]');
xlabel('t [s]');


%% Roll
axisRpy(1) = subplot(3, 4, 3:4, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
roll = ypr(:, 3);
line(t, roll, ...
    'Parent', axisRpy(1), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', lineColor(4, :) ...
    ); 
hold on;
roll = ypr2(:, 3);
line(t, roll, ...
    'Parent', axisRpy(1), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', [1 1 1] ...
    ); 

xlim([0 t(end)]);
ylim([-180 180]);

title('Roll', ...
    'Color', titleColor ...
    );
ylabel('angle [°]');
xlabel('t [s]');
legendHandle = legend('roll');
set(legendHandle, 'TextColor', [1 1 1]);

%% Pitch
axisRpy(2) = subplot(3, 4, 7:8, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
pitch = ypr(:, 2);
line(t, pitch, ...
    'Parent', axisRpy(2), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', lineColor(5, :) ...
    ); 
hold on;
pitch = ypr2(:, 2);
line(t, pitch, ...
    'Parent', axisRpy(2), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', [1 1 1] ...
    ); 

xlim([0 t(end)]);
ylim([-180 180]);

title('Pitch (elevation)', ...
    'Color', titleColor ...
    );
ylabel('angle [°]');
xlabel('t [s]');
legendHandle = legend('pitch');
set(legendHandle, 'TextColor', [1 1 1]);

%% Yaw
axisRpy(3) = subplot(3, 4, 11:12, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', axesColor, ...
    'YGrid', 'on', ...
    'YColor', axesColor, ...
    'Color', plotBackground ...
    );

t = time;
yaw = ypr(:, 1);
line(t, yaw, ...
    'Parent', axisRpy(3), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', lineColor(6, :) ...
    ); 
hold on;
yaw = ypr2(:, 1);
line(t, yaw, ...
    'Parent', axisRpy(3), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'MarkerSize', 2, ...
    'Color', [1 1 1] ...
    ); 

xlim([0 t(end)]);
ylim([-180 180]);

title('Yaw (azimuth)', ...
    'Color', titleColor ...
    );
ylabel('angle [°]');
xlabel('t [s]');
legendHandle = legend('yaw');
set(legendHandle, 'TextColor', [1 1 1]);

%% Plot refining
% link the axes
linkaxes([axisAccel axisCompass axisRpy], 'x');
%linkaxes(axisRpy, 'x');