function txyzCalibrated = calibrateAccelerometer(txyz)

    [accelerometerCalibrationData, ~] = loadCalibrationData();
    offset = accelerometerCalibrationData.offset;

    if size(txyz,2) == 4
        txyzCalibrated = [ ...
            txyz(:,2) - offset(1), ...
            txyz(:,3) - offset(2), ...
            txyz(:,4) - offset(3)];
        txyzCalibrated = [txyz(:,1) txyzCalibrated(:, 1:3)];
    else % assume XYZ values
        txyzCalibrated = [ ...
            txyz(:,1) - offset(1), ...
            txyz(:,2) - offset(2), ...
            txyz(:,3) - offset(3)];
    end

end