close all; clear all; home;

% define the data set folder
dataSetFolder = '../../data/set-1/tilt-sphere';

%% Load the data
[accelerometer, gyroscope, magnetometer, temperature] = loadData(dataSetFolder);

%% Plot data
figureHandle = figure('Name', 'Raw sensor data', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis
lineColor(4, :) = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

%% Compass
% compass: x/y axis
axisCompass(1) = subplot(3, 3, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'Color', plotBackground ...
    );

x = magnetometer(:, 2);
y = magnetometer(:, 3);

line(x, y, ...
    'Parent', axisCompass(1), ...
    'Color', lineColor(4, :) ...
    );
axis square;

title('x/y plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');

% compass: x/z axis
axisCompass(1) = subplot(3, 3, 4, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

x = magnetometer(:, 2);
z = magnetometer(:, 4);

line(x, z, ...
    'Parent', axisCompass(1), ...
    'Color', lineColor(4, :) ...
    );
axis square;

title('x/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_z [Gs]');

% compass: y/z axis
axisCompass(2) = subplot(3, 3, 7, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(2, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

y = magnetometer(:, 3);
z = magnetometer(:, 4);

line(y, z, ...
    'Parent', axisCompass(2), ...
    'Color', lineColor(4, :) ...
    );
axis square;

title('y/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_y [Gs]');
ylabel('B_z [Gs]');

%% Compass
% compass: x, y and z axis
axisCompass(3) = subplot(3, 3, [2 3 5 6 8 9], ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'ZGrid', 'on', ...
    'ZColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

x = magnetometer(:, 2);
y = magnetometer(:, 3);
z = magnetometer(:, 4);

line(x, y, z, ...
    'Parent', axisCompass(3), ...
    'Color', lineColor(4, :) ...
    );
view(3);
axis square;

title('HMC5883L Magnetometer', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');
zlabel('B_z [Gs]');
