clc; clear all; home;

% define the data set folder
dataSetFolder = '../../data/set-1/tilt-sphere';

%% Load the data
% note that this also works for accelerometer calibration
[~, ~, magnetometer, temperature] = loadData(dataSetFolder);

% Fetch axes
x = magnetometer(:, 2);
y = magnetometer(:, 3);
z = magnetometer(:, 4);

% Calibrate sensor
[correction, xc, yc, zc] = calibrateByEllipseFitting(x, y, z);

%% Plot data
figureHandle = figure('Name', 'Sensor Calibration / Ellipse Fitting', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis
lineColor(4, :) = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

axisCompass(1) = subplot(1, 2, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'ZGrid', 'on', ...
    'ZColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

axisCompass(2) = subplot(1, 2, 2, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'ZGrid', 'on', ...
    'ZColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

linkprop(axisCompass, 'CameraPosition');

title('Raw Sensor Data', ...
    'Parent', axisCompass(1), ...
    'Color', titleColor ...
    );

title('Compensated Sensor Data', ...
    'Parent', axisCompass(2), ...
    'Color', titleColor ...
    );

% plot raw
line(x, ...
     y, ...
     z, ...
    'Parent', axisCompass(1), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'Color', [0.8 0.8 0.8], ...
    'MarkerSize', 1);
hold on;

axis(axisCompass, 'square');
xlabel(axisCompass(1), 'x'); xlim(axisCompass(1), [-1 1]); 
ylabel(axisCompass(1), 'y'); ylim(axisCompass(1), [-1 1]); 
zlabel(axisCompass(1), 'z'); zlim(axisCompass(1), [-1 1]);
view(axisCompass(1), 3);

% plot compensated
line(xc, ...
     yc, ...
     zc, ...
    'Parent', axisCompass(2), ...
    'LineStyle', 'none', ...
    'Marker', '.', ...
    'Color', [0.8 0.8 0.8], ...
    'MarkerSize', 1);
hold on;

axis square
xlabel(axisCompass(2), 'x'); xlim(axisCompass(2), [-1 1]); 
ylabel(axisCompass(2), 'y'); ylim(axisCompass(2), [-1 1]); 
zlabel(axisCompass(2), 'z'); zlim(axisCompass(2), [-1 1]);
view(axisCompass(2), 3);
rotate3d;

%% Plot Semi-Axes for raw points

% prepare semi-axis plots
semiaxis(1, :) = evecs(:,1) * radii(1);
semiaxis(2, :) = evecs(:,2) * radii(2);
semiaxis(3, :) = evecs(:,3) * radii(3);
semiaxisVectorEnd(1, :) = evecs(:,1);
semiaxisVectorEnd(2, :) = evecs(:,2);
semiaxisVectorEnd(3, :) = evecs(:,3);

% plot semi-axes
line( [0 semiaxis(1,1)] + center(1), ...
      [0 semiaxis(1,2)] + center(2), ...
      [0 semiaxis(1,3)] + center(3), ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(3, :), ...
      'LineWidth', 2)
line( [0 semiaxis(2,1)] + center(1), ...
      [0 semiaxis(2,2)] + center(2), ...
      [0 semiaxis(2,3)] + center(3), ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(2, :), ...
      'LineWidth', 2)
line( [0 semiaxis(3,1)] + center(1), ...
      [0 semiaxis(3,2)] + center(2), ...
      [0 semiaxis(3,3)] + center(3), ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(1, :), ...
      'LineWidth', 2)

% plot semi-axis vectors
line( [semiaxis(1, 1) semiaxisVectorEnd(1,1)] + center(1), ...
      [semiaxis(1, 2) semiaxisVectorEnd(1,2)] + center(2), ...
      [semiaxis(1, 3) semiaxisVectorEnd(1,3)] + center(3), ...
      'LineStyle', ':', ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(3, :), ...
      'LineWidth', 2)
line( [semiaxis(2, 1) semiaxisVectorEnd(2,1)] + center(1), ...
      [semiaxis(2, 2) semiaxisVectorEnd(2,2)] + center(2), ...
      [semiaxis(2, 3) semiaxisVectorEnd(2,3)] + center(3), ...
      'LineStyle', ':', ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(2, :), ...
      'LineWidth', 2)
line( [semiaxis(3, 1) semiaxisVectorEnd(3,1)] + center(1), ...
      [semiaxis(3, 2) semiaxisVectorEnd(3,2)] + center(2), ...
      [semiaxis(3, 3) semiaxisVectorEnd(3,3)] + center(3), ...
      'LineStyle', ':', ...
      'Parent', axisCompass(1), ...
      'Color', lineColor(1, :), ...
      'LineWidth', 2)

%% Plot Semi-Axes for calibrated points

% prepare semi-axis plots
semiaxis(1, :) = A * evecs(:,1) * radii(1);
semiaxis(2, :) = A * evecs(:,2) * radii(2);
semiaxis(3, :) = A * evecs(:,3) * radii(3);
semiaxisVectorEnd(1, :) = evecs(:,1);
semiaxisVectorEnd(2, :) = evecs(:,2);
semiaxisVectorEnd(3, :) = evecs(:,3);

% plot semi-axes
line( [0 semiaxis(1,1)], ...
      [0 semiaxis(1,2)], ...
      [0 semiaxis(1,3)], ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(3, :), ...
      'LineWidth', 2)
line( [0 semiaxis(2,1)], ...
      [0 semiaxis(2,2)], ...
      [0 semiaxis(2,3)], ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(2, :), ...
      'LineWidth', 2)
line( [0 semiaxis(3,1)], ...
      [0 semiaxis(3,2)], ...
      [0 semiaxis(3,3)], ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(1, :), ...
      'LineWidth', 2)

% plot semi-axis vectors
line( [semiaxis(1, 1) semiaxisVectorEnd(1,1)], ...
      [semiaxis(1, 2) semiaxisVectorEnd(1,2)], ...
      [semiaxis(1, 3) semiaxisVectorEnd(1,3)], ...
      'LineStyle', ':', ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(3, :), ...
      'LineWidth', 2)
line( [semiaxis(2, 1) semiaxisVectorEnd(2,1)], ...
      [semiaxis(2, 2) semiaxisVectorEnd(2,2)], ...
      [semiaxis(2, 3) semiaxisVectorEnd(2,3)], ...
      'LineStyle', ':', ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(2, :), ...
      'LineWidth', 2)
line( [semiaxis(3, 1) semiaxisVectorEnd(3,1)], ...
      [semiaxis(3, 2) semiaxisVectorEnd(3,2)], ...
      [semiaxis(3, 3) semiaxisVectorEnd(3,3)], ...
      'LineStyle', ':', ...
      'Parent', axisCompass(2), ...
      'Color', lineColor(1, :), ...
      'LineWidth', 2)