close all; clear all; home;

% define the data set folder
dataSetFolder = '../../data/set-1/tilt-sphere';

%% Load the data
[~, ~, magnetometer, temperature] = loadData(dataSetFolder);

% Fetch axes
x = magnetometer(:, 2);
y = magnetometer(:, 3);
z = magnetometer(:, 4);

% Calculate hard-iron factor
% In theory, a simple average (mean(magnetometer(:, 2:4)))
% would do the trick, but that does not take into account the
% actual number of measurements taken. Averging the component-wise
% min and max values yields better results but is prone to errors
% due to outliers in the measurement.
hardIronOffset(1) = (max(x)+min(x))/2;
hardIronOffset(2) = (max(y)+min(y))/2;
hardIronOffset(3) = (max(z)+min(z))/2;

disp('Calculated hard iron offset: ');
disp(num2str(hardIronOffset));

%% Plot data
figureHandle = figure('Name', 'Raw sensor data', ...
    'NumberTitle', 'off', ...
    'Color', [0.027 0.211 0.259] ...
    );

% define base colors
lineColor(1, :) = [1 0.25 0]; % x axis
lineColor(2, :) = [0.5 1 0]; % y axis
lineColor(3, :) = [0 0.5 1]; % z axis
lineColor(4, :) = [1 1 1];
axesColor = [0.473 0.473 0.473];
plotBackground = [0.15 0.15 0.15];
titleColor = [1 1 1];

%% Compass
% compass: x/y axis
axisCompass(1) = subplot(3, 3, 1, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'Color', plotBackground ...
    );

line(x, y, ...
    'Parent', axisCompass(1), ...
    'Color', lineColor(4, :) ...
    );
hold on;

axis square;
xlim([-1 1]);
ylim([-1 1]);

title('x/y plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');

% compass: x/z axis
axisCompass(2) = subplot(3, 3, 4, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

line(x, z, ...
    'Parent', axisCompass(2), ...
    'Color', lineColor(4, :) ...
    );

axis square;
xlim([-1 1]);
ylim([-1 1]);

title('x/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_z [Gs]');

% compass: y/z axis
axisCompass(3) = subplot(3, 3, 7, ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(2, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(3, :), ...
    'Color', plotBackground ...
    );

line(y, z, ...
    'Parent', axisCompass(3), ...
    'Color', lineColor(4, :) ...
    );

axis square;
xlim([-1 1]);
ylim([-1 1]);

title('y/z plane', ...
    'Color', titleColor ...
    );
xlabel('B_y [Gs]');
ylabel('B_z [Gs]');

%% Compass
% compass: x, y and z axis
axisCompass(4) = subplot(3, 3, [2 3 5 6 8 9], ...
    'Parent', figureHandle, ...
    'XGrid', 'on', ...
    'XColor', lineColor(1, :), ...
    'YGrid', 'on', ...
    'YColor', lineColor(2, :), ...
    'ZGrid', 'on', ...
    'ZColor', lineColor(3, :), ...
    'Color', plotBackground, ...
    'LineStyle', ':' ...
    );

lol = line(x, y, z, ...
    'Parent', axisCompass(4), ...
    'Color', lineColor(4, :)*0.5...
    );

view(3);
axis square;
xlim([-1 1]);
ylim([-1 1]);
zlim([-1 1]);

hold on;
line(x - hardIronOffset(1), ...
    y - hardIronOffset(2), ...
    z - hardIronOffset(3), ...
    'Parent', axisCompass(4), ...
    'Color', [0.9 0.5 0], ...
    'LineStyle', '-' ...
    );

title('HMC5883L Magnetometer', ...
    'Color', titleColor ...
    );
xlabel('B_x [Gs]');
ylabel('B_y [Gs]');
zlabel('B_z [Gs]');
